basePath: /api
definitions:
  domain.User:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      sex:
        type: string
      surname:
        type: string
    type: object
  request.Store:
    properties:
      name:
        maxLength: 255
        minLength: 2
        type: string
      patronymic:
        maxLength: 255
        minLength: 2
        type: string
      surname:
        maxLength: 255
        minLength: 2
        type: string
    required:
    - name
    - surname
    type: object
  request.Update:
    properties:
      age:
        type: integer
      name:
        maxLength: 255
        minLength: 2
        type: string
      nationality:
        maxLength: 255
        minLength: 2
        type: string
      patronymic:
        maxLength: 255
        minLength: 2
        type: string
      sex:
        maxLength: 255
        minLength: 2
        type: string
      surname:
        maxLength: 255
        minLength: 2
        type: string
    required:
    - name
    - surname
    type: object
  response.Delete:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  response.Error:
    properties:
      error:
        type: string
      errors:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
  response.Index:
    properties:
      status:
        type: string
      users:
        items:
          $ref: '#/definitions/domain.User'
        type: array
    type: object
  response.Show:
    properties:
      status:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  response.Store:
    properties:
      status:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  response.Update:
    properties:
      status:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
info:
  contact:
    email: eerzho@gmail.com
    name: Zhanbolat
  description: test task for effective mobile
  title: Effective mobile
  version: "1.0"
paths:
  /users:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: name
        in: query
        name: name
        type: string
      - description: surname
        in: query
        name: surname
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Index'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - users
    post:
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Store'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Store'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - users
  /users/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Delete'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - users
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Show'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - users
    patch:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Update'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Update'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - users
swagger: "2.0"
